# Configuration for the RandomThings paper plugin
#
# If any assistance is needed, feel free to contact me on Discord: funnyboy_roks#0001.

# A vacuum hopper will make all items within 5 blocks teleport to the hopper.
# A vacuum hopper can be made by placing a purple carpet on top of a hopper.
# It will be broken when the carpet or hopper is broken.
# Technical Details:
#     The vacuum hopper collects items every 20 ticks (1 second)
#     It just places the items on top of the hopper, so the hopper speed is still important to keep in mind.
vacuum-hoppers: true

# Makes blackstone renewable via lava spreading to a block adjacent to blue ice on top of soul sand.
# Similarly to basalt, but with soul sand rather than soul soil.
renewable-blackstone: true

# Makes deepslate renewable via the same mechanic as stone and cobblestone generators,
# but when below y=0, cobble generators make cobbled deepslate and stone generators make deepslate.
renewable-deepslate: true

# Makes it such that when a lightning strike happens within 4 blocks of a guardian, it turns into an elder guardian.
renewable-sponges: true

# When a silver fish exits a block, it will drop a piece of gravel with it.
silver-fish-drop-gravel: true

# When one right-clicks on a fully grown crop, it will harvest the crop and replant it.
right-click-harvest-crops: true

# Allows one to spam sneak to apply a bonemeal effect to surrounding blocks.
twerk-bonemeal: true

# When a dispenser uses a pickaxe, shovel, axe, or shears on a block, it will break it with the tool
# and drop the item on the ground as if a player broke it with the tool.
dispenser-break-blocks: true

# When a dispenser uses a hoe, it will convert the block in front of it as if a hoe was used on it.
# Dirt/Grass Block -> Farmland    and    Coarse Dirt -> Dirt
dispenser-till-blocks: true
