# Configuration for the RandomThings paper plugin
#
# If any assistance is needed, feel free to contact me on Discord: funnyboy_roks#0001.

# A vacuum hopper will make all items within 5 blocks teleport to the hopper.
# A vacuum hopper can be made by placing a purple carpet on top of a hopper.
# It will be broken when the carpet or hopper is broken.
# Technical Details:
#     The vacuum hopper collects items every 20 ticks (1 second)
#     It just places the items on top of the hopper, so the hopper speed is still important to keep in mind.
vacuum-hoppers: false

# Makes blackstone renewable via lava spreading to a block adjacent to blue ice on top of soul sand.
# Similarly to basalt, but with soul sand rather than soul soil.
renewable-blackstone: false

# Makes deepslate renewable via the same mechanic as stone and cobblestone generators,
# but when below y=0, cobble generators make cobbled deepslate and stone generators make deepslate.
renewable-deepslate: false

# Andesite becomes renewable through stone generators on top of andesite.
# If the block below a generated stone block is andesite, the stone will turn into andesite.
renewable-andesite: false

# Makes it such that when a lightning strike happens within 4 blocks of a guardian, it turns into an elder guardian.
renewable-sponges: false

# When a silver fish exits a block, it will drop a piece of gravel with it.
silver-fish-drop-gravel: false

# When one right-clicks on a fully grown crop, it will harvest the crop and replant it.
right-click-harvest-crops: false

# Allows one to spam sneak to apply a bonemeal effect to surrounding blocks.
twerk-bonemeal: false

# When a dispenser uses a pickaxe, shovel, axe, or shears on a block, it will break it with the tool
# and drop the item on the ground as if a player broke it with the tool.
dispenser-break-blocks: false

# When a dispenser uses a hoe, it will convert the block in front of it as if a hoe was used on it.
# Dirt/Grass Block -> Farmland    and    Coarse Dirt -> Dirt
dispenser-till-blocks: false

# Dispensers work with cauldrons and buckets
dispenser-cauldrons: false

# Budding amethyst can be pushed by pistons (but not pulled)
# Be careful -- budding amethyst can be crushed by pushing it into a block
movable-amethyst: false

# Magic mirrors made from combining an ender pearl, a compass, and 16 levels in an anvil can be used
# to teleport to the player's respawn location.
magic-mirror: false

# Sapling/Propagule items dropped on grass or dirt for 5-15 seconds will place the sapling on the ground
auto-saplings: false

# Elevators are made by placing an iron pressure plate on top of a wool block of any colour
# When jumping/sneaking on an elevator, you will go up/down to the closest elevator of the same colour.
elevators: false