name: RandomThings
version: '${project.version}'
main: com.funnyboyroks.randomthings.RandomThings
description: A collection of random things that add interesting aspects to the game.
api-version: 1.19
author: funnyboy_roks
website: https://modrinth.com/plugin/randomthings
